name: Bug Report
description: Report software bugs to the developer
title: "[Bug]: "
labels: ["bug", "新提交"]
assignees:
  - XFTY
body:
  - type: markdown
    attributes:
      value: |
        Thank you for providing feedback to the software developer!  
        Where exactly is the problem (qwq)?

  - type: input
    id: Bug-Description
    attributes:
      label: Software Exception/Fault Description
      description: Please briefly explain the software fault to the developer.
      placeholder: Please enter here
    validations:
      required: true

  - type: textarea
    id: To-Reproduce
    attributes:
      label: Steps to Reproduce the Issue
      description: |
        How did this problem occur? The developer needs the tutorial...  
        If possible, you can also provide screenshots.

      placeholder: |
        1. First do this...  
        2. Then do that...  
        3. Finally do this again...  
        
        Don't write like this when actually filling!
    validations:
      required: true

  - type: input
    id: Expected-Behavior
    attributes:
      label: Expected Software Behavior
      description: After following the steps you mentioned above, what should the software do?
      placeholder: Please enter here
    validations:
      required: true

  - type: dropdown
    id: HC-Version
    attributes:
      label: HomeworkChecker Version
      description: |
        Which version of HomeworkChecker are you running?  

      options:
        - 1.4-snapshot
        - 1.3-stable
        - 1.2-snapshot
        - 1.1-snapshot
      default: 0
    validations:
      required: true

  - type: textarea
    id: Additional-Context
    attributes:
      label: Additional Information
      description: |
        You can add information you want to explain here

      placeholder: |
        Please enter here
    validations:
      required: false